# Generated by Django 5.2.7 on 2025-11-23 07:37

from django.db import migrations

def set_default_dish_types(apps, schema_editor):
    Dish = apps.get_model('billing_app', 'Dish')

    # Set default dish_type = 'meals' for existing dishes
    Dish.objects.filter(dish_type__isnull=True).update(dish_type='meals')
    Dish.objects.filter(dish_type='').update(dish_type='meals')

    # For dishes with meal_type='morning', set dish_type = 'addons'
    Dish.objects.filter(meal_type='morning').update(dish_type='addons')

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_dish_options_and_more'),  # <--- IMPORTANT
    ]

    operations = [
        migrations.RunPython(set_default_dish_types, reverse_migration),
    ]
