# Generated by Django 5.2.7 on 2025-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_person_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
