# Generated by Django 5.2.7 on 2025-12-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_auto_20251123_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishDisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_order_info', to='billing_app.dish')),
            ],
            options={
                'verbose_name': 'Dish Display Order',
                'verbose_name_plural': 'Dish Display Orders',
                'ordering': ['meal_type', 'order'],
                'indexes': [models.Index(fields=['meal_type', 'order'], name='billing_app_meal_ty_8094f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('meal_type', 'order'), name='unique_order_per_mealtype')],
            },
        ),
    ]
