# Generated by Django 5.2.7 on 2025-12-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_dishdisplayorder'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishdisplayorder',
            name='unique_order_per_mealtype',
        ),
    ]
